export const GET_DINGE = 'GET_DINGE';
export const GET_LOCAL_DINGE = 'GET_LOCAL_DINGE';
export const GET_DING = 'GET_DING';
export const POST_DING = 'POST_DING';
export const UPDATE_DING_LOCATION = 'UPDATE_DING_LOCATION';
export const UPDATE_DING_LOCATION2 = 'UPDATE_DING_LOCATION2';
export const LIKE_DING = 'LIKE_DING';
export const UNLIKE_DING = 'UNLIKE_DING';
export const REPORT_DING = 'REPORT_DING';
export const POST_COMMENT = 'POST_COMMENT';

export const GET_AUTH_EVENTS = 'GET_AUTH_EVENTS';
export const GET_LOCAL_EVENTS = 'GET_LOCAL_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const UPDATE_EVENT_LOCATION = 'UPDATE_EVENT_LOCATION';
export const CREATE_EVENT = 'CREATE_EVENT';

export const SET_IMAGE = 'SET_IMAGE';
export const RESET_IMAGE = 'RESET_IMAGE';

export const GET_USER = 'GET_USER';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const GET_AUTH_USER = 'GET_AUTH_USER';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';
export const PROFILE_UPDATE_REDUX = 'PROFILE_UPDATE_REDUX';

export const FORM_INPUT_UPDATE = 'FORM_INPUT_UPDATE';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';

export const SET_LOCATION = 'SET_LOCATION';

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const GET_VERIFICATION_CODE = 'GET_VERIFICATION_CODE';
export const CODE_VERIFIED = 'CODE_VERIFIED';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_DID_TRY_AL = 'SET_DID_TRY_AL';

export const INPUT_CHANGE = 'INPUT_CHANGE';
export const INPUT_BLUR = 'INPUT_BLUR';
