export enum ActionTypes {
  GET_DINGE = 'GET_DINGE',
  GET_DING_BY_ID = 'GET_DING_BY_ID',
  REMOVE_DING = 'REMOVE_DING',
  GET_LOCAL_DINGE = 'GET_LOCAL_DINGE',
  GET_LOCAL_EVENTS = 'GET_LOCAL_EVENTS',
  ADD_MESSAGE = 'ADD_MESSAGE',
  REMOVE_MESSAGE = 'REMOVE_MESSAGE',
  AUTHENTICATE = 'AUTHENTICATE',
  SET_AUTH_USER = 'SET_AUTH_USER',
  GET_AUTH_USER = 'GET_AUTH_USER',
  SET_DID_TRY_AL = 'SET_DID_TRY_AL',
  LOGOUT = 'LOGOUT',
}
